### PR TITLE
dev: Refactor attribute resolution into `Data\BlockAttributeResolver`

### LINKED ISSUE #261: CoreVideo attributes `controls` always return true
When I add CoreVideo on Gutenberg and try to disable `controls` attribute, preview on Gutenberg works with no display for controls, but GraphQL return `true` in attributes
image
image

| Plugins                  | Version |
|--------------------------|---------|
| WPGraphQL                | 1.28.0  |
| WPGraphQL Content Blocks | 4.0.1   |
| WPGraphQL for ACF        | 2.4.1   |
| WordPress        | 6.6.1   |

- [x] I can confirm that the issue appear with minimal plugin requirement (WPGraphQL and WPGraphQL Content Blocks)

### PR DESCRIPTION
**Pull request by justlevine**
## What

This PR refactors attribute resolution handling out of `\Blocks\Block.php` and into a new `\Data\BlockAttributeResolver` class.

Additionally, method internals have been cleaned up and parameter/internal variables renamed for readability.

## Why

- fixes #261 (covered by https://github.com/rtCamp/wp-graphql-content-blocks/blob/331486097e719fc8138cb5affbad9aa160ec5072/tests/unit/CoreVideoTest.php#L93 )

Long term, this is part of fixing attribute resolution and performance / implementing a block `Model`. This work has been cherry-picked out for reviewability, as it contains _no breaking changes_ or new features/fixes/enhancements. 

## How

`Block::resolve_block_attributes_recursive()` now calls `Data\BlockAttributeResolver::resolve_block_attribute()`. The method has been marked `@internal` since' we're probably going to change it once a Block model has been fully implemented.

### CODE REVIEW

**Comment by justlevine** [comment]
Rebased post #279

**Review by jasonbahl — CHANGES_REQUESTED** [review]
I pulled this down and the first query I tried to execute: 

```graphql
{
  post(id: 121, idType: DATABASE_ID) {
    id
    title
    date
    editorBlocks(flat: false) {
      __typename
      ...CoreTable
    }
  }
}

fragment CoreTable on CoreTable {
  anchor
  apiVersion
  attributes {
    textColor
    style
    lock
    head {
      cells {
        align
        content
        tag
        scope
      }
    }
    hasFixedLayout
    gradient
    foot {
      cells {
        align
        content
        scope
        tag
      }
    }
    fontSize
    fontFamily
    className
    caption
    borderColor
    body {
      cells {
        align
        content
        scope
        tag
      }
    }
    backgroundColor
    anchor
    align
  }
  renderedHtml
}
```

Led to this error: 

```json
    {
      "debugMessage": "WPGraphQL\\ContentBlocks\\Data\\BlockAttributeResolver::parse_query_source(): Argument #3 ($attribute_values) must be of type array, null given, called in /Users/jason.bahl/Sites/libs/wp-graphql-content-blocks/includes/Data/BlockAttributeResolver.php on line 48",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 20,
          "column": 5
        }
      ],
      "path": [
        "post",
        "editorBlocks",
        2,
        "attributes",
        "head"
      ],
      "trace": [
        {
          "file": "/Users/jason.bahl/Sites/libs/wp-graphql-content-blocks/includes/Data/BlockAttributeResolver.php",
          "line": 48,
          "call": "WPGraphQL\\ContentBlocks\\Data\\BlockAttributeResolver::parse_query_source('<figure class=\"wp-block-table\"><table><thead><tr><th class=\"has-text-align-center\" data-align=\"center\">Header Label 1</th><th></th></tr></thead><tbody><tr><td class=\"has-text-align-center\" data-align=\"center\">1:1</td><td>1:2</td></tr><tr><td class=\"has-text-align-center\" data-align=\"center\">2:1</td><td>2:2</td></tr></tbody><tfoot><tr><td class=\"has-text-align-center\" data-align=\"center\">Footer Label 1</td><td>Footer Label 2</td></tr></tfoot></table></figure>', array(5), null)"
        },
```

**Comment by justlevine** [comment]
@jasonbahl thanks for the catch! Fixed in https://github.com/wpengine/wp-graphql-content-blocks/pull/284/commits/7b7599fe7eb8c06b87b944026383eafd21cbfe15

I also rebased the plugin on #290 (so `CoreVideoTest` actually runs now), which allowed me to find/fix the regression in #229 that was causing attributes to return null/incorrect.

**Comment by justlevine** [comment]
> @jasonbahl thanks for the catch! Fixed in [7b7599f](https://github.com/wpengine/wp-graphql-content-blocks/commit/7b7599fe7eb8c06b87b944026383eafd21cbfe15)
> 
> I also rebased the plugin on #290 (so `CoreVideoTest` actually runs now), which allowed me to find/fix the regression in #229 that was causing attributes to return null/incorrect.

#286 got merged directly, so the remaining relevant changes here are just the above (diff: https://github.com/wpengine/wp-graphql-content-blocks/pull/284/files/c1cf11875bc1dee74f15a5240e2ac93ee38beed2..1bd300aaa9fbd5f4cf8622c92b94e49ae8ad80c3)

**Reminder**: #290 still needs to be merged first

**Comment by justlevine** [comment]
This was merged as part of #293

**Pull request closed without merging**
