### PR TITLE
fix: prevent fatal errors with DOMHelpers methods by improving typesafety and returning early

### PR DESCRIPTION
**Pull request by justlevine**
## What

This PR:
- Updates the methods in the `DOMHelpers` class to return early if no HTML is passed to the method.
- Improves type safety of the `DOMHelpers` methods by inlining their types to the method signatures. To maintain back-compatiblity, the old methods have been deprecated, with `snake_case` alternatives created with the stricter signatures.

> [!IMPORTANT]
> This PR is based on #256 which should be merged first.
> The relevant diff for this PR is: 5b59fe3a68a434748710e8682e1df38c7637bb0f

## Why

Without returning early, numerous DIDOM methods we call internally can fatal error. The improved type safety is to prevent this sort of issue leaking through again in the future.

## To Test

1. Add the following placeholder image block to a page (extracted from a TT4 pattern):

   ```html
   <!-- wp:image {"width":"150px","aspectRatio":"4/3","scale":"contain","linkDestination":"none"} -->
   <figure class="wp-block-image is-resized"><img alt="" style="aspect-ratio:4/3;object-fit:contain;width:150px"/></figure>
   <!-- /wp:image -->
   ```

2. Query for `CoreBlockImageAttributes`:

   ```graphql
   {
    nodeByUri(uri: "/sample-page") { # change the URI to your page
      ... on NodeWithEditorBlocks {
        editorBlocks {
          __typename
          ... on CoreImage {
            attributes {
              width
              alt
            }
          }
        }
      }
     }
   }
   ```

3. Ensure no errors, and `attributes` are returned.
  
## Screenshots
-  Before:
image

- After:
image

### CODE REVIEW

**Comment by justlevine** [comment]
@jasonbahl for your review

**Review by theodesp — APPROVED** [review]

**Comment by theodesp** [comment]
@justlevine there is a small conflict there; if you could resolve it, I can merge. Thank you

**Comment by justlevine** [comment]
@theodesp conflicts resolved ✔️

**Comment by justlevine** [comment]
#258 will fix the failing ci

Please let me know what else I can do to help advance this ticket.

**Comment by theodesp** [comment]
@justlevine I merged https://github.com/wpengine/wp-graphql-content-blocks/pull/258

**Comment by justlevine** [comment]
@theodesp I merged `main` into the PR, If you trigger the CI again, you should see them all passing now (besides SonarQube)

**Review by theodesp — APPROVED** [review]

**Pull request merged**
